Mentee landing page hero v1
DaveBFlanikJr/menternshift-frontend pull request #13
Opened 2024-04-14 15:04 UTC by sylfort

As requested by @Naokimi I will start making PRs using v1, v2 terminology to make them more atomic.

This is v1 of hero component for the Mentee landing page.

2024-04-17 00:46 UTC, Naokimi commented
@DaveBFlanikJr @FefesG5 please review it first so then mentors can proceed to review

2024-04-17 01:42 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
HeroRightImage.svg and hero_left_underline.svg is a little inconsistent. Please select one to follow when adding for all public assets.

2024-04-17 01:43 UTC, FefesG5 commented on src/assets/HeroRightImage.svg
HeroRightImage.svg and hero_left_underline.svg naming is inconsitent. We should stick to a single way to name the public asset images.

2024-04-17 01:45 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +import HeroRightImage from "../assets/HeroRightImage.svg";
I mentioned for consistent naming for the images. Best to change the import file name once a naming convention is set for public asset images.

2024-04-17 01:47 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
Is this red the following the CSS color set by the design team/Figma design or a substitute/placeholder for now?

2024-04-17 01:53 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  font-family: "Lato";
If possible, have a backup font-family text incase "Lato" cannot be downloaded/ imported by the client.

Should look like this HeroParagraph {
    font-family: "Lato", Arial, sans-serif;
}

I know I'm a hypocrite as I don't always follow this convention too.

2024-04-17 01:56 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
Just a reminder about the border red 1px solid if it is the same as the Figma design

2024-04-17 01:58 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +            <img src={hero_left_underline} alt="clicking a line Image" />
alt="clicking a line Image" this description is unclear. Could we get a more descriptive name?

2024-04-17 02:00 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
Reminder for the confirmation of the red color use is same as the Figma design?

2024-04-17 02:02 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  img {
Can we have a more descriptive name for the img tag? Is this suppose to be the hero image?

2024-04-17 02:04 UTC, FefesG5 reviewed
I agree to most of all the code. Just minor nitpicks.

2024-04-18 15:41 UTC, sylfort commented on src/assets/HeroRightImage.svg
Apparently snake_case is the recommended one for naming image assets.

2024-04-18 15:41 UTC, sylfort commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
Just a placeholder to better see the layout of the components.

2024-04-18 15:47 UTC, sylfort commented on src/components/MenteeLandingPageHero.tsx
> +  img {
This is the hero_left_underline.svg image. This is the only image inside the HeroLeft component so I thought a long name for it was not needed.

2024-04-18 15:49 UTC, sylfort commented on src/components/MenteeLandingPageHero.tsx
> +            <img src={hero_left_underline} alt="clicking a line Image" />
how about "decorative underline for emphasis in the h1" ?

2024-04-18 23:52 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
Add a comment after the 1px solid red; // placeholder for layout components positioning. Remove from production code.

2024-04-18 23:54 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  font-family: "Lato";
Did you add the sans-serif default to line 45 as well?

2024-04-18 23:55 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +            <img src={hero_left_underline} alt="clicking a line Image" />
This new alt is much better. Change the alt to the "decorative underline for emphasis in the h1"

2024-04-18 23:58 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +import HeroRightImage from "../assets/HeroRightImage.svg";
change the import name and the public asset name to snakecase to match the hero_left_underline one.

2024-04-18 23:59 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
```suggestion
  border: 1px solid red; // placeholder for layout components positioning. Remove from production code.
```

2024-04-18 23:59 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
```suggestion
  border: 1px solid red; // placeholder for layout components positioning. Remove from production code.
```

2024-04-19 00:00 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  img {
This is cool not a problem since there is only one image.

2024-04-19 00:01 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  font-family: "Lato";
```suggestion
  font-family: "Lato",  sans-serif;
```

2024-04-19 00:01 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  border: 1px solid red;
```suggestion
  border: 1px solid red; // placeholder for layout components positioning. Remove from production code.
```

2024-04-19 00:02 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +            <img src={hero_left_underline} alt="clicking a line Image" />
```suggestion
            <img src={hero_left_underline} alt="decorative underline for emphasis in the h1" />
```

2024-04-19 00:03 UTC, FefesG5 requested changes
All my suggestions have be solved. Just waiting for the changes, should be good to approve.

2024-04-20 15:08 UTC, sylfort commented
> All my suggestions have be solved. Just waiting for the changes, should be good to approve.

Done making the changes suggested. Thanks for the review!

2024-04-20 15:22 UTC, DaveBFlanikJr commented
@sylfort I think everything looks fine

2024-04-20 15:23 UTC, DaveBFlanikJr approved these changes

2024-04-20 15:23 UTC, DaveBFlanikJr commented on src/pages/MenteeLandingPage.tsx
> +export const MenteeLandingPage: React.FC = () => {
Everything looks good. 

I was wondering, since the main pages are all going to be the same components (mainly just the content will change) can we abstract them out? 

I think we will be redoing a lot of the css and components at this rate. 

(For example, the landing page body can be a component we use for the mentor page, project page, mentee page, etc.. Then we can inherit and use it across all three)

What do you think @sylfort  @FefesG5 

CC: @frontendmentor0

2024-04-20 15:34 UTC, sylfort commented on src/assets/HeroRightImage.svg
I have renamed HeroRightImage.svg to hero_right_image.svg

2024-04-21 00:09 UTC, FefesG5 commented on src/components/MenteeLandingPageHero.tsx
> +  width: 621px;
I do agree we should switch to em or rem, but we don't have a figma design for small screen or responsive ones (normally we would have a global css to base off our rem values from). I think for now we would have to stick to px to be honest.

2024-04-21 00:13 UTC, FefesG5 approved these changes
Looks good to me. Nice.

2024-04-21 23:23 UTC, Naokimi commented
@sylfort can you please rebase your branch and cleanup your commit history before a mentor reviews it?

2024-04-22 03:35 UTC, sylfort commented
> @sylfort can you please rebase your branch and cleanup your commit history before a mentor reviews it?

Done

2024-04-22 11:36 UTC, Naokimi commented on src/App.tsx
> +// import MentorProfile from "./pages/MentorProfile";
question:
why the commented code?

2024-04-22 11:36 UTC, Naokimi commented on src/App.tsx
> +      {/* <MentorProfile /> */}
question:
why the commented code?

2024-04-22 11:48 UTC, Naokimi approved these changes

2024-04-22 11:49 UTC, merged